title: Site

tabs:

  # content tab
  content:
    label: pages
    icon: text
    columns:

      - width: 4/4
        sections:
          pages:
            type: pages
            sortBy: title
            template:
              - default
              - home
              - contact-us
              - find-us
              - htmlsitemap
              - search
              - news
              - testimonials


  # blog tab
  blog:
    label: News Articles
    icon: document

    pages: news

    columns:

      left:
        width: 1/3
        sections:
          drafts:
            extends: sections/articles
            headline: Drafts
            status: draft

          unlisted:
            extends: sections/articles
            headline: In Review
            status: unlisted

      right:
        width: 2/3
        sections:
          listed:
            extends: sections/articles
            headline: Published
            status: listed
            layout: cards

  # cookie banner tab
  cookie:
    label: Cookie Banner Text
    icon: circle-nested
    type: fields
    fields:
      cookie: sections/cookie

  # site details tab
  site:
    label: Site Details
    icon: book
    columns:

      - width: 1/3
        fields:
          companyname:
            label: Company Name
            type: text
          author:
            label: Authors or Owners Name
            type: text
          address:
            label: Address
            type: text
          street:
            label: Street
            type: text
          village:
            label: Village
            type: text
          city:
            label: City
            type: text
          county:
            label: County
            type: text
          postcode:
            label: Postcode
            type: text
          email:
            label: Email
            type: email
          phone:
            label: Phone
            type: tel
          mobile:
            label: Mobile
            type: tel
          inter:
            label: International Format Phone Number
            type: tel

      - width: 1/3
        fields:
          long:
            label: Longditude
            type: text
          lat:
            label: Latitude
            type: text
          hasmap:
            label: Google Map URL
            type: text
          open:
            label: Opening Hours
            type: text
          sameas:
            label: Social Media Links (with comma between each)
            type: text
          pricerange:
            label: Price Range of Services or Products (without £ symbol to start)
            type: text
          companylogo:
            label: Company Logo
            type: files
            layout: cards
            info: "{{ file.dimensions }}"
            max: 1
          companyimage:
            label: Company Image
            type: files
            layout: cards
            info: "{{ file.dimensions }}"
            max: 1

      - width: 1/3
        fields:
          facebookurl:
            label: Facebook URL (ie. https://facebook.com)
            type: text
          linkedinurl:
            label: LinkedIn URL (ie. https://linkedin.com)
            type: text
          twitterurl:
            label: Twitter URL (ie. https://twitter.com#me)
            type: text
          twittercreator:
            label: Twitter Creator (ie. @me)
            type: text

# navigation tab
  navigation:
    icon: bars
    columns:
      - width: 1/2
        sections:
          mainnavigation:
            type: fields
            fields:
              mainnavigation:
                label: Main Navigation
                type: navigation
                levels: 3
                help: Main Navigation
      - width: 1/2
        sections:
          footernavigation:
            type: fields
            fields:
              footernavigation:
                label: First Footer Navigation
                type: navigation
                levels: 1
                help: First Footer Navigation
          secondfooternavigation:
            type: fields
            fields:
              secondfooternavigation:
                label: Second Footer Navigation
                type: navigation
                levels: 1
                help: Second Footer Navigation
